window.MARKET_DATA = {
  "asOf": "2026-09-24",
  "updatedAt": "2026-09-25 12:56 Asia/Taipei",
  "watchlist": [
    {
      "ticker": "NOW",
      "name": "ServiceNow",
      "price": 137.78,
      "dayPct": -2.13,
      "rsi14": 54.154,
      "ma20": 138.89,
      "ma50": 125.15,
      "ma200": 116.81,
      "revenueGrowth": 24.0,
      "fcfMargin": 31.0,
      "sbcRevenue": 14.8,
      "forwardPE": 27.5,
      "evSales": 9.9,
      "pFcf": 31.2,
      "aiOpportunity": 9,
      "companyQuality": 9.5,
      "valuation": 8,
      "riskReward": 9,
      "bearPct": -20,
      "basePct": 24,
      "bullPct": 45,
      "coreMetric": "Q2 subscription revenue $3.877B, +24.5% YoY; cRPO $13.2B, +21%; RPO $29.0B, +21%; AI ACV >$1B; FY26 subscription-revenue outlook raised",
      "thesis": "Enterprise workflow + AI Control Tower; system of action for human and agent workflows, with agentic deployments scaling rapidly.",
      "risk": "Agentic AI could abstract the UI; M&A and SBC discipline matter.",
      "preMarketPrice": null,
      "preMarketPct": null,
      "preMarketAsOf": null,
      "preMarketState": "CLOSED"
    },
    {
      "ticker": "ZS",
      "name": "Zscaler",
      "price": 214.64,
      "dayPct": 0.09,
      "rsi14": 70.484,
      "ma20": 184.66,
      "ma50": 171.67,
      "ma200": 167.86,
      "revenueGrowth": 24.9,
      "fcfMargin": 23.2,
      "sbcRevenue": 24.5,
      "forwardPE": 38.3,
      "evSales": 10.0,
      "pFcf": 44.9,
      "aiOpportunity": 9.5,
      "companyQuality": 8.5,
      "valuation": 7,
      "riskReward": 7.5,
      "bearPct": -30,
      "basePct": 15,
      "bullPct": 45,
      "coreMetric": "FY26 Q4 revenue $898.2M, +25% YoY; ARR $3.771B, +25% including Red Canary / +20% organic; net new ARR $246M; FY26 FCF margin 23%; RPO ~$7.4B, +27%",
      "thesis": "Zero Trust for users, workloads and AI agents; Agentic SOC + data security create meaningful AI-era expansion vectors.",
      "risk": "Organic ARR growth is closer to 20% after adjusting for Red Canary; FY27 rerating requires sustained organic acceleration and clean acquisition integration.",
      "preMarketPrice": null,
      "preMarketPct": null,
      "preMarketAsOf": null,
      "preMarketState": "CLOSED"
    },
    {
      "ticker": "RBRK",
      "name": "Rubrik",
      "price": 113.8,
      "dayPct": -1.53,
      "rsi14": 66.586,
      "ma20": 98.61,
      "ma50": 91.02,
      "ma200": 70.89,
      "revenueGrowth": 37.9,
      "fcfMargin": 18.6,
      "sbcRevenue": 22.2,
      "forwardPE": 148.2,
      "evSales": 14.9,
      "pFcf": 81.8,
      "aiOpportunity": 9.5,
      "companyQuality": 8.5,
      "valuation": 6,
      "riskReward": 9,
      "bearPct": -35,
      "basePct": 30,
      "bullPct": 70,
      "coreMetric": "FY27 Q2 subscription ARR $1.66B, +33% YoY; cloud ARR $1.48B, +39%; revenue $427.3M, +38%; FCF $65.7M / 15% margin; FY27 ARR/revenue/FCF guidance raised",
      "thesis": "Cyber resilience + Rubrik AI + Agent Cloud combine recovery, data security and autonomous AI-agent protection; improving operating leverage adds a second earnings driver.",
      "risk": "Premium multiple and still-large SBC require >30% ARR growth and continued margin expansion; execution risk rises as the platform broadens into agentic security.",
      "preMarketPrice": null,
      "preMarketPct": null,
      "preMarketAsOf": null,
      "preMarketState": "CLOSED"
    },
    {
      "ticker": "FTNT",
      "name": "Fortinet",
      "price": 178.67,
      "dayPct": -0.04,
      "rsi14": 64.803,
      "ma20": 165.76,
      "ma50": 161.12,
      "ma200": 115.29,
      "revenueGrowth": 25.6,
      "fcfMargin": 41.4,
      "sbcRevenue": 3.9,
      "forwardPE": 47.3,
      "evSales": 16.9,
      "pFcf": 42.1,
      "aiOpportunity": 8.5,
      "companyQuality": 9.5,
      "valuation": 6.5,
      "riskReward": 8.5,
      "bearPct": -22,
      "basePct": 18,
      "bullPct": 35,
      "coreMetric": "Secure networking/SASE growth with unusually strong cash generation; FY26 revenue and billings outlook was raised after Q1; Virtue AI acquisition expands runtime/agentic AI protection",
      "thesis": "Secure networking + SASE + AI workload protection; Virtue AI expands continuous validation and runtime security for autonomous AI systems.",
      "risk": "Valuation is no longer cheap; AI-security purity and software mix remain lower than ZS/CRWD.",
      "preMarketPrice": null,
      "preMarketPct": null,
      "preMarketAsOf": null,
      "preMarketState": "CLOSED"
    },
    {
      "ticker": "MU",
      "name": "Micron Technology",
      "price": 1080.53,
      "dayPct": 0.81,
      "rsi14": 63.021,
      "ma20": 986.8,
      "ma50": 937.03,
      "ma200": 656.8,
      "revenueGrowth": 345.7,
      "fcfMargin": 29.0,
      "sbcRevenue": 1.3,
      "forwardPE": 6.8,
      "evSales": 13.3,
      "pFcf": 46.6,
      "aiOpportunity": 9.5,
      "companyQuality": 8.8,
      "valuation": 8.5,
      "riskReward": 8.5,
      "bearPct": -35,
      "basePct": 25,
      "bullPct": 65,
      "coreMetric": "FQ3 revenue $41.46B vs $9.30B YoY; FQ4 revenue guide $50B +/- $1B with ~86% gross margin; HBM4 in high-volume shipments; next earnings Sep 30, 2026",
      "thesis": "AI memory cycle, HBM4 demand and data-center DRAM/NAND growth; strategic customer agreements and constrained advanced-memory supply support exceptional earnings power.",
      "risk": "Highly cyclical memory pricing and record capex intensity; expectations are extreme after the large rerating and Sep 30 earnings create event risk.",
      "preMarketPrice": null,
      "preMarketPct": null,
      "preMarketAsOf": null,
      "preMarketState": "CLOSED"
    },
    {
      "ticker": "CRWD",
      "name": "CrowdStrike",
      "price": 259.67,
      "dayPct": -1.07,
      "rsi14": 66.918,
      "ma20": 226.03,
      "ma50": 210.8,
      "ma200": 148.88,
      "revenueGrowth": 25.8,
      "fcfMargin": 28.2,
      "sbcRevenue": 23.1,
      "forwardPE": 161.7,
      "evSales": 48.5,
      "pFcf": 174.6,
      "aiOpportunity": 10,
      "companyQuality": 9.5,
      "valuation": 3,
      "riskReward": 6.5,
      "bearPct": -30,
      "basePct": 15,
      "bullPct": 45,
      "coreMetric": "FY27 Q2 revenue $1.47B, +26%; ARR $5.84B, +25%; record net new ARR $333M, +51%; Falcon Flex ARR $2.29B, +101%; FCF $377M / 26% margin; FY27 net-new-ARR growth guide raised to 34% midpoint",
      "thesis": "Cloud-native security platform spanning endpoint, identity, cloud, SIEM and AI-agent security; accelerating net-new ARR and Falcon Flex adoption strengthen the consolidation thesis.",
      "risk": "Exceptional execution is already reflected in an extreme valuation; even modest growth or multiple normalization can create sharp drawdowns.",
      "preMarketPrice": null,
      "preMarketPct": null,
      "preMarketAsOf": null,
      "preMarketState": "CLOSED"
    },
    {
      "ticker": "SNOW",
      "name": "Snowflake",
      "price": 334.0,
      "dayPct": -0.24,
      "rsi14": 54.024,
      "ma20": 330.71,
      "ma50": 314.42,
      "ma200": 223.95,
      "revenueGrowth": 35.1,
      "fcfMargin": 22.0,
      "sbcRevenue": 30.2,
      "forwardPE": 110.8,
      "evSales": 21.7,
      "pFcf": 98.7,
      "aiOpportunity": 9.8,
      "companyQuality": 9,
      "valuation": 5,
      "riskReward": 7.5,
      "bearPct": -30,
      "basePct": 25,
      "bullPct": 55,
      "coreMetric": "FY27 Q2 revenue $1.55B, +35%; product revenue $1.492B, +37%; RPO $9.0B, +30%; NRR 126%; FY27 product-revenue guide raised to $6.07B / +36%; adjusted FCF margin guide 23%",
      "thesis": "Enterprise data + AI consumption platform; product-revenue growth has reaccelerated for three straight quarters while CoCo/CoWork adoption shows AI workloads are becoming a material consumption driver.",
      "risk": "Premium valuation and high SBC remain the key constraints; competition from Databricks and hyperscalers requires sustained product velocity and consumption growth.",
      "preMarketPrice": null,
      "preMarketPct": null,
      "preMarketAsOf": null,
      "preMarketState": "CLOSED"
    },
    {
      "ticker": "BE",
      "name": "Bloom Energy",
      "price": 266.65,
      "dayPct": -3.1,
      "rsi14": 56.152,
      "ma20": 252.95,
      "ma50": 228.04,
      "ma200": 202.07,
      "revenueGrowth": 165.5,
      "fcfMargin": 20.1,
      "sbcRevenue": 5.9,
      "forwardPE": 54.1,
      "evSales": 25.3,
      "pFcf": 125.7,
      "aiOpportunity": 8.5,
      "companyQuality": 7.5,
      "valuation": 4,
      "riskReward": 6.5,
      "bearPct": -40,
      "basePct": 18,
      "bullPct": 60,
      "coreMetric": "Q2 revenue $1.065B, +165.5% YoY; product revenue +215%; FY26 revenue guidance raised to $3.9B-$4.2B (~100% growth at midpoint); AI data-center power demand remains the key catalyst",
      "thesis": "On-site power for data centers; AI-driven electricity demand can accelerate deployments where grid interconnection is the bottleneck.",
      "risk": "Project execution, financing needs, customer concentration, policy exposure and volatile expectations.",
      "preMarketPrice": null,
      "preMarketPct": null,
      "preMarketAsOf": null,
      "preMarketState": "CLOSED"
    },
    {
      "ticker": "GLW",
      "name": "Corning",
      "price": 154.15,
      "dayPct": -0.21,
      "rsi14": 49.745,
      "ma20": 153.02,
      "ma50": 152.63,
      "ma200": 148.08,
      "revenueGrowth": 16.6,
      "fcfMargin": 14.1,
      "sbcRevenue": 2.5,
      "forwardPE": 35.3,
      "evSales": 8.3,
      "pFcf": 55.4,
      "aiOpportunity": 8,
      "companyQuality": 8.5,
      "valuation": 6,
      "riskReward": 7,
      "bearPct": -25,
      "basePct": 22,
      "bullPct": 45,
      "coreMetric": "Q2 core sales $4.74B, +17%; Optical Communications sales $2.07B, +32%; Enterprise Networks +65% with GenAI products growing faster; Sep 11 ATM program allows up to $2B of common-stock issuance",
      "thesis": "Optical connectivity and fiber demand from AI data-center buildouts; accelerating Enterprise Networks sales provide a direct read-through from GenAI infrastructure capex.",
      "risk": "AI exposure is indirect and partly cyclical; the $2B ATM equity program adds dilution and technical-overhang risk.",
      "preMarketPrice": null,
      "preMarketPct": null,
      "preMarketAsOf": null,
      "preMarketState": "CLOSED"
    }
  ],
  "automation": {
    "marketData": "Yahoo Finance Chart API daily bars",
    "schedule": "07:17, 08:17, 09:17 and 11:17 Asia/Taipei with holiday-safe no-op",
    "autoFields": [
      "price",
      "dayPct",
      "rsi14",
      "ma20",
      "ma50",
      "ma200",
      "revenueGrowth",
      "fcfMargin",
      "sbcRevenue",
      "forwardPE",
      "evSales",
      "pFcf"
    ],
    "preservedFields": [
      "aiOpportunity",
      "companyQuality",
      "valuation",
      "riskReward",
      "thesis",
      "risk",
      "bearPct",
      "basePct",
      "bullPct",
      "ARR/cRPO/billings"
    ]
  },
  "preMarketStatus": "CLOSED",
  "preMarketUpdatedAt": "2026-09-21 23:57 Asia/Taipei",
  "twWatchlist": [],
  "twAsOf": null
};
