window.MARKET_DATA = {
  "asOf": "2026-09-18",
  "updatedAt": "2026-09-19 14:31 Asia/Taipei",
  "watchlist": [
    {
      "ticker": "NOW",
      "name": "ServiceNow",
      "price": 135.47,
      "dayPct": -2.17,
      "rsi14": 52.905,
      "ma20": 136.7,
      "ma50": 122.66,
      "ma200": 117.39,
      "revenueGrowth": 24.0,
      "fcfMargin": 31.0,
      "sbcRevenue": 14.8,
      "forwardPE": 27.1,
      "evSales": 9.8,
      "pFcf": 30.6,
      "aiOpportunity": 9.0,
      "companyQuality": 9.5,
      "valuation": 8.0,
      "riskReward": 9.0,
      "bearPct": -20,
      "basePct": 24,
      "bullPct": 45,
      "coreMetric": "Q2 subscription revenue $3.877B, +24.5% YoY; cRPO $13.2B, +21%; AI ACV >$1B",
      "thesis": "Enterprise workflow + AI Control Tower; system of action for human and agent workflows.",
      "risk": "Agentic AI could abstract the UI; M&A and SBC discipline matter.",
      "preMarketPrice": null,
      "preMarketPct": null,
      "preMarketAsOf": null,
      "preMarketState": "CLOSED"
    },
    {
      "ticker": "ZS",
      "name": "Zscaler",
      "price": 197.31,
      "dayPct": -0.08,
      "rsi14": 63.295,
      "ma20": 179.16,
      "ma50": 167.61,
      "ma200": 168.31,
      "revenueGrowth": 24.9,
      "fcfMargin": 23.2,
      "sbcRevenue": 24.5,
      "forwardPE": 35.2,
      "evSales": 9.1,
      "pFcf": 41.3,
      "aiOpportunity": 9.5,
      "companyQuality": 8.5,
      "valuation": 7.0,
      "riskReward": 8.0,
      "bearPct": -30,
      "basePct": 15,
      "bullPct": 45,
      "coreMetric": "FY26 Q4 revenue growth ~25%; FY27 growth guide implies material deceleration",
      "thesis": "Zero Trust for users, workloads and AI agents; Agentic SOC + data security.",
      "risk": "FY27 guide implies slower growth; rerating requires organic ARR re-acceleration.",
      "preMarketPrice": null,
      "preMarketPct": null,
      "preMarketAsOf": null,
      "preMarketState": "CLOSED"
    },
    {
      "ticker": "RBRK",
      "name": "Rubrik",
      "price": 106.71,
      "dayPct": -1.04,
      "rsi14": 62.856,
      "ma20": 96.03,
      "ma50": 89.3,
      "ma200": 70.24,
      "revenueGrowth": 37.9,
      "fcfMargin": 18.6,
      "sbcRevenue": 22.2,
      "forwardPE": 139.0,
      "evSales": 14.0,
      "pFcf": 76.7,
      "aiOpportunity": 9.5,
      "companyQuality": 8.0,
      "valuation": 6.0,
      "riskReward": 8.5,
      "bearPct": -35,
      "basePct": 28,
      "bullPct": 65,
      "coreMetric": "Subscription ARR remains the key growth KPI; cyber-resilience demand remains strong",
      "thesis": "Cyber resilience + Agent Cloud + recovery / rewind after agent or attack failures.",
      "risk": "Still GAAP loss-making; high SBC and multiple require >30% growth to persist.",
      "preMarketPrice": null,
      "preMarketPct": null,
      "preMarketAsOf": null,
      "preMarketState": "CLOSED"
    },
    {
      "ticker": "FTNT",
      "name": "Fortinet",
      "price": 169.84,
      "dayPct": -1.59,
      "rsi14": 58.003,
      "ma20": 162.09,
      "ma50": 160.16,
      "ma200": 113.88,
      "revenueGrowth": 25.6,
      "fcfMargin": 41.4,
      "sbcRevenue": 3.9,
      "forwardPE": 45.0,
      "evSales": 16.1,
      "pFcf": 40.0,
      "aiOpportunity": 8.0,
      "companyQuality": 9.5,
      "valuation": 6.5,
      "riskReward": 8.5,
      "bearPct": -22,
      "basePct": 18,
      "bullPct": 35,
      "coreMetric": "Secure networking/SASE growth with unusually strong cash generation",
      "thesis": "Secure networking + SASE + AI workload protection; Virtue AI expands agent/runtime security.",
      "risk": "Valuation is no longer cheap; AI-security purity lower than ZS/CRWD.",
      "preMarketPrice": null,
      "preMarketPct": null,
      "preMarketAsOf": null,
      "preMarketState": "CLOSED"
    },
    {
      "ticker": "MU",
      "name": "Micron Technology",
      "price": 1015.8,
      "dayPct": 3.92,
      "rsi14": 58.277,
      "ma20": 959.6,
      "ma50": 927.26,
      "ma200": 640.02,
      "revenueGrowth": 345.7,
      "fcfMargin": 29.0,
      "sbcRevenue": 1.3,
      "forwardPE": 6.5,
      "evSales": 12.5,
      "pFcf": 43.8,
      "aiOpportunity": 9.5,
      "companyQuality": 8.8,
      "valuation": 8.5,
      "riskReward": 8.5,
      "bearPct": -35,
      "basePct": 25,
      "bullPct": 65,
      "coreMetric": "HBM/AI-server memory remains the primary cycle driver; next earnings Sep 30, 2026",
      "thesis": "AI memory cycle, HBM demand and data-center DRAM/NAND growth; high-capacity server memory demand remains strong.",
      "risk": "Highly cyclical memory pricing and capex intensity; RSI is now in an overbought zone after the latest rally.",
      "preMarketPrice": null,
      "preMarketPct": null,
      "preMarketAsOf": null,
      "preMarketState": "CLOSED"
    },
    {
      "ticker": "CRWD",
      "name": "CrowdStrike",
      "price": 237.65,
      "dayPct": -3.28,
      "rsi14": 60.412,
      "ma20": 215.86,
      "ma50": 207.08,
      "ma200": 146.97,
      "revenueGrowth": 25.8,
      "fcfMargin": 28.2,
      "sbcRevenue": 23.1,
      "forwardPE": 148.0,
      "evSales": 44.3,
      "pFcf": 159.8,
      "aiOpportunity": 10.0,
      "companyQuality": 9.5,
      "valuation": 3.0,
      "riskReward": 6.0,
      "bearPct": -30,
      "basePct": 12,
      "bullPct": 40,
      "coreMetric": "Falcon platform expansion and AI-security demand remain core ARR drivers",
      "thesis": "Cloud-native security platform spanning endpoint, identity, cloud, SIEM and AI-agent security.",
      "risk": "Premium valuation leaves little room for execution misses or multiple compression.",
      "preMarketPrice": null,
      "preMarketPct": null,
      "preMarketAsOf": null,
      "preMarketState": "CLOSED"
    },
    {
      "ticker": "SNOW",
      "name": "Snowflake",
      "price": 332.43,
      "dayPct": -1.76,
      "rsi14": 53.997,
      "ma20": 328.93,
      "ma50": 310.38,
      "ma200": 222.71,
      "revenueGrowth": 35.1,
      "fcfMargin": 22.0,
      "sbcRevenue": 30.2,
      "forwardPE": 110.3,
      "evSales": 21.6,
      "pFcf": 98.3,
      "aiOpportunity": 9.5,
      "companyQuality": 8.8,
      "valuation": 5.0,
      "riskReward": 7.0,
      "bearPct": -30,
      "basePct": 20,
      "bullPct": 50,
      "coreMetric": "Product-consumption growth and remaining performance obligations are the key leading indicators",
      "thesis": "Enterprise data + AI consumption platform; AI workloads can accelerate product consumption.",
      "risk": "Premium valuation, high SBC and intense competition from Databricks and hyperscalers.",
      "preMarketPrice": null,
      "preMarketPct": null,
      "preMarketAsOf": null,
      "preMarketState": "CLOSED"
    },
    {
      "ticker": "BE",
      "name": "Bloom Energy",
      "price": 265.63,
      "dayPct": -5.39,
      "rsi14": 57.527,
      "ma20": 240.45,
      "ma50": 225.43,
      "ma200": 198.84,
      "revenueGrowth": 165.5,
      "fcfMargin": 20.1,
      "sbcRevenue": 5.9,
      "forwardPE": 53.9,
      "evSales": 25.2,
      "pFcf": 125.2,
      "aiOpportunity": 8.5,
      "companyQuality": 7.5,
      "valuation": 4.0,
      "riskReward": 6.5,
      "bearPct": -40,
      "basePct": 18,
      "bullPct": 60,
      "coreMetric": "Q2 revenue growth ~166%; AI data-center power demand remains the key catalyst",
      "thesis": "On-site power for data centers; AI-driven electricity demand can accelerate deployments.",
      "risk": "Project execution, financing needs, policy exposure and volatile expectations.",
      "preMarketPrice": null,
      "preMarketPct": null,
      "preMarketAsOf": null,
      "preMarketState": "CLOSED"
    },
    {
      "ticker": "GLW",
      "name": "Corning",
      "price": 150.13,
      "dayPct": 1.58,
      "rsi14": 47.338,
      "ma20": 151.37,
      "ma50": 154.77,
      "ma200": 146.63,
      "revenueGrowth": 16.6,
      "fcfMargin": 14.1,
      "sbcRevenue": 2.5,
      "forwardPE": 34.5,
      "evSales": 8.1,
      "pFcf": 54.0,
      "aiOpportunity": 8.0,
      "companyQuality": 8.5,
      "valuation": 6.0,
      "riskReward": 7.0,
      "bearPct": -25,
      "basePct": 22,
      "bullPct": 45,
      "coreMetric": "Optical communications demand remains strong; Sep 11 ATM program allows up to $2B of common-stock issuance",
      "thesis": "Optical connectivity and fiber demand from AI data-center buildouts.",
      "risk": "AI exposure is indirect; the new ATM equity program adds dilution/technical-overhang risk.",
      "preMarketPrice": null,
      "preMarketPct": null,
      "preMarketAsOf": null,
      "preMarketState": "CLOSED"
    }
  ],
  "automation": {
    "marketData": "Yahoo Finance explicit-date download",
    "schedule": "Tue-Sat 09:35, 11:35 and 13:35 Asia/Taipei",
    "autoFields": [
      "price",
      "dayPct",
      "rsi14",
      "ma20",
      "ma50",
      "ma200",
      "revenueGrowth",
      "fcfMargin",
      "sbcRevenue",
      "forwardPE",
      "evSales",
      "pFcf"
    ],
    "preservedFields": [
      "aiOpportunity",
      "companyQuality",
      "valuation",
      "riskReward",
      "thesis",
      "risk",
      "bearPct",
      "basePct",
      "bullPct",
      "ARR/cRPO/billings"
    ]
  },
  "preMarketStatus": "CLOSED",
  "preMarketUpdatedAt": "2026-09-19 09:55 Asia/Taipei"
};
